<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element xmlns:quer="http://api.geotrust.com/webtrust/query"/>
  <xs:element xmlns:quer="http://api.geotrust.com/webtrust/query"/>
</xs:schema>
